### PR TITLE
edit: feature: github action to auto update tailscale version (#18)

### PR DESCRIPTION
**Pull request by patte**
simplify and cleanup: https://github.com/patte/fly-tailscale-exit/pull/18

### CODE REVIEW

**Comment by stepbrobd** [comment]
Nice!

Also, it seems Fly.io have a GitHub Action: <https://github.com/superfly/flyctl-actions>, do you think it's necessary to integrate this into auto update cron job?

**Comment by patte** [comment]
@StepBroBD Thank you for the PR, awesome :tada: 

I had to merge the PR at this point to be able to trigger it. Or so I thought, the path was still wrong `.github/workflow` instead of `.github/workflows` (the ending s was missing). That's now fixed, as well as when nothing changed, the workflow [doesn't error](https://github.com/patte/fly-tailscale-exit/commit/eb51b4ea6df2fbeca0e4d1560a5de20826a5f69d). Had to do this on main because actions :shrug: 
I did the refactoring mainly to not having to relay on 2 actions (actions/checkout@v3 and actions-js/push@master) because I'm paranoid about actions with push permissions.

Thanks again!

re the fly action: that would enable to deploy it automatically to fly. This would require a script to also enable this new vms as `exit-node` in tailscale and thus would require a tailscale API to be stored in github. I don't have time for this right now, but if you are willing to give it a try, that be awesome of course!

**Comment by stepbrobd** [comment]
Thanks for your reply! Awesome project!

I am planing to write a shell script to delete all machines with fly.io tag (need to be customized) and redeploy with the new Dockerfile (users would need to create API keys for both Tailscale and Fly.io). I'll update the readme in another PR.

Also, for this to work, users would need to change ACL on Tailscale: <https://tailscale.com/kb/1018/acls/?q=Auto%20approvers#auto-approvers-for-routes-and-exit-nodes>, so they wouldn't need to approve exit route one by one.

If you think these looks good, I'll start working on it.

All input (extra requirement) are welcomed!

**Comment by patte** [comment]
So `start.sh` would `--advertise-tags=tag:fly.io-exit`. Which would allow to have a script that (on update):
- get's the old machines from with the tag tailscale
- deploys to fly (which adds these to tailscale, auto approved by ACL)
- deletes the old machines

It would be cool if it could be done in this "zero downtime" mode (get old-machines => deploy => if successfull: delete old-machines) :wink:

That would be very nice! I'm happy to review a PR anytime.

**Comment by stepbrobd** [comment]
Got it, thanks!

I'll update the documentation in another PR.

**Pull request merged**
